//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MintADB.Wpf.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MintADB.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Navigation & General
        // ═══════════════════════════════════════════════════════════════

        public static string NavOptimize {
            get {
                return ResourceManager.GetString("NavOptimize", resourceCulture);
            }
        }

        public static string NavTools {
            get {
                return ResourceManager.GetString("NavTools", resourceCulture);
            }
        }

        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }

        public static string RefreshDeviceList {
            get {
                return ResourceManager.GetString("RefreshDeviceList", resourceCulture);
            }
        }

        public static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }

        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }

        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }

        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }

        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }

        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }

        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Optimize Tab
        // ═══════════════════════════════════════════════════════════════

        public static string XiaomiChina {
            get {
                return ResourceManager.GetString("XiaomiChina", resourceCulture);
            }
        }

        public static string OptimizeSubtitle {
            get {
                return ResourceManager.GetString("OptimizeSubtitle", resourceCulture);
            }
        }

        public static string ROM {
            get {
                return ResourceManager.GetString("ROM", resourceCulture);
            }
        }

        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }

        public static string SystemOptions {
            get {
                return ResourceManager.GetString("SystemOptions", resourceCulture);
            }
        }

        public static string DisableAndroidRestrictions {
            get {
                return ResourceManager.GetString("DisableAndroidRestrictions", resourceCulture);
            }
        }

        public static string UnlockXiaomiChinaControl {
            get {
                return ResourceManager.GetString("UnlockXiaomiChinaControl", resourceCulture);
            }
        }

        public static string AutoGrantPermissions {
            get {
                return ResourceManager.GetString("AutoGrantPermissions", resourceCulture);
            }
        }

        public static string DisableMIUIOptimization {
            get {
                return ResourceManager.GetString("DisableMIUIOptimization", resourceCulture);
            }
        }

        public static string ChangeRegionCNtoGlobal {
            get {
                return ResourceManager.GetString("ChangeRegionCNtoGlobal", resourceCulture);
            }
        }

        public static string DisableMIUIAnalytics {
            get {
                return ResourceManager.GetString("DisableMIUIAnalytics", resourceCulture);
            }
        }

        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }

        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }

        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }

        public static string PlayStore {
            get {
                return ResourceManager.GetString("PlayStore", resourceCulture);
            }
        }

        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        public static string ROMBloat {
            get {
                return ResourceManager.GetString("ROMBloat", resourceCulture);
            }
        }

        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }

        public static string ScanApps {
            get {
                return ResourceManager.GetString("ScanApps", resourceCulture);
            }
        }

        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }

        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }

        public static string SearchByNameOrPackage {
            get {
                return ResourceManager.GetString("SearchByNameOrPackage", resourceCulture);
            }
        }

        public static string RemoveDisable {
            get {
                return ResourceManager.GetString("RemoveDisable", resourceCulture);
            }
        }

        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }

        public static string UninstallDisableApps {
            get {
                return ResourceManager.GetString("UninstallDisableApps", resourceCulture);
            }
        }

        public static string UninstallDisableAppsDesc {
            get {
                return ResourceManager.GetString("UninstallDisableAppsDesc", resourceCulture);
            }
        }

        public static string UninstallDisable {
            get {
                return ResourceManager.GetString("UninstallDisable", resourceCulture);
            }
        }

        public static string UninstallSystemShell {
            get {
                return ResourceManager.GetString("UninstallSystemShell", resourceCulture);
            }
        }

        public static string DisableApps {
            get {
                return ResourceManager.GetString("DisableApps", resourceCulture);
            }
        }

        public static string UninstallAllBloat {
            get {
                return ResourceManager.GetString("UninstallAllBloat", resourceCulture);
            }
        }

        public static string UninstallFromFile {
            get {
                return ResourceManager.GetString("UninstallFromFile", resourceCulture);
            }
        }

        public static string RestoreApps {
            get {
                return ResourceManager.GetString("RestoreApps", resourceCulture);
            }
        }

        public static string RestoreAppsDesc {
            get {
                return ResourceManager.GetString("RestoreAppsDesc", resourceCulture);
            }
        }

        public static string RestoreSelected {
            get {
                return ResourceManager.GetString("RestoreSelected", resourceCulture);
            }
        }

        public static string EnableSelected {
            get {
                return ResourceManager.GetString("EnableSelected", resourceCulture);
            }
        }

        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }

        public static string QuickActionsDesc {
            get {
                return ResourceManager.GetString("QuickActionsDesc", resourceCulture);
            }
        }

        public static string FixNotifications {
            get {
                return ResourceManager.GetString("FixNotifications", resourceCulture);
            }
        }

        public static string GrantPermissions {
            get {
                return ResourceManager.GetString("GrantPermissions", resourceCulture);
            }
        }

        public static string FullOptimize {
            get {
                return ResourceManager.GetString("FullOptimize", resourceCulture);
            }
        }

        public static string BackupAppList {
            get {
                return ResourceManager.GetString("BackupAppList", resourceCulture);
            }
        }

        public static string RestoreFromBackup {
            get {
                return ResourceManager.GetString("RestoreFromBackup", resourceCulture);
            }
        }

        public static string SafeDebloat {
            get {
                return ResourceManager.GetString("SafeDebloat", resourceCulture);
            }
        }

        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }

        public static string UndoHistory {
            get {
                return ResourceManager.GetString("UndoHistory", resourceCulture);
            }
        }

        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Tools Tab
        // ═══════════════════════════════════════════════════════════════

        public static string ADBTools {
            get {
                return ResourceManager.GetString("ADBTools", resourceCulture);
            }
        }

        public static string ADBToolsSubtitle {
            get {
                return ResourceManager.GetString("ADBToolsSubtitle", resourceCulture);
            }
        }

        public static string RiskLegend {
            get {
                return ResourceManager.GetString("RiskLegend", resourceCulture);
            }
        }

        public static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }

        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }

        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        public static string Dangerous {
            get {
                return ResourceManager.GetString("Dangerous", resourceCulture);
            }
        }

        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }

        public static string ToolsApps {
            get {
                return ResourceManager.GetString("ToolsApps", resourceCulture);
            }
        }

        public static string Scrcpy {
            get {
                return ResourceManager.GetString("Scrcpy", resourceCulture);
            }
        }

        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }

        public static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }

        public static string Tweaks {
            get {
                return ResourceManager.GetString("Tweaks", resourceCulture);
            }
        }

        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }

        public static string Fastboot {
            get {
                return ResourceManager.GetString("Fastboot", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Basic Tools
        // ═══════════════════════════════════════════════════════════════

        public static string ADBFastbootDriver {
            get {
                return ResourceManager.GetString("ADBFastbootDriver", resourceCulture);
            }
        }

        public static string DeployTools {
            get {
                return ResourceManager.GetString("DeployTools", resourceCulture);
            }
        }

        public static string InstallUSBDriver {
            get {
                return ResourceManager.GetString("InstallUSBDriver", resourceCulture);
            }
        }

        public static string RestartADB {
            get {
                return ResourceManager.GetString("RestartADB", resourceCulture);
            }
        }

        public static string DriverFolder {
            get {
                return ResourceManager.GetString("DriverFolder", resourceCulture);
            }
        }

        public static string DeviceManager {
            get {
                return ResourceManager.GetString("DeviceManager", resourceCulture);
            }
        }

        public static string CheckVersion {
            get {
                return ResourceManager.GetString("CheckVersion", resourceCulture);
            }
        }

        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }

        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }

        public static string Bootloader {
            get {
                return ResourceManager.GetString("Bootloader", resourceCulture);
            }
        }

        public static string Sideload {
            get {
                return ResourceManager.GetString("Sideload", resourceCulture);
            }
        }

        public static string EDL {
            get {
                return ResourceManager.GetString("EDL", resourceCulture);
            }
        }

        public static string APKStore {
            get {
                return ResourceManager.GetString("APKStore", resourceCulture);
            }
        }

        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        public static string PushAll {
            get {
                return ResourceManager.GetString("PushAll", resourceCulture);
            }
        }

        public static string InstallAll {
            get {
                return ResourceManager.GetString("InstallAll", resourceCulture);
            }
        }

        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }

        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }

        public static string InstallAPK {
            get {
                return ResourceManager.GetString("InstallAPK", resourceCulture);
            }
        }

        public static string BackupAPK {
            get {
                return ResourceManager.GetString("BackupAPK", resourceCulture);
            }
        }

        public static string OpenApp {
            get {
                return ResourceManager.GetString("OpenApp", resourceCulture);
            }
        }

        public static string ClearData1App {
            get {
                return ResourceManager.GetString("ClearData1App", resourceCulture);
            }
        }

        public static string ForceStop1App {
            get {
                return ResourceManager.GetString("ForceStop1App", resourceCulture);
            }
        }

        public static string ClearDataMultiple {
            get {
                return ResourceManager.GetString("ClearDataMultiple", resourceCulture);
            }
        }

        public static string PushPullFileExplorer {
            get {
                return ResourceManager.GetString("PushPullFileExplorer", resourceCulture);
            }
        }

        public static string PushDesc {
            get {
                return ResourceManager.GetString("PushDesc", resourceCulture);
            }
        }

        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }

        public static string LocalFile {
            get {
                return ResourceManager.GetString("LocalFile", resourceCulture);
            }
        }

        public static string RemotePath {
            get {
                return ResourceManager.GetString("RemotePath", resourceCulture);
            }
        }

        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }

        public static string PullSavedTo {
            get {
                return ResourceManager.GetString("PullSavedTo", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Tools Apps Tab
        // ═══════════════════════════════════════════════════════════════

        public static string UserAppsPlayStore {
            get {
                return ResourceManager.GetString("UserAppsPlayStore", resourceCulture);
            }
        }

        public static string UserAppsPlayStoreDesc {
            get {
                return ResourceManager.GetString("UserAppsPlayStoreDesc", resourceCulture);
            }
        }

        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }

        public static string PermissionsSelected {
            get {
                return ResourceManager.GetString("PermissionsSelected", resourceCulture);
            }
        }

        public static string QuickPresets {
            get {
                return ResourceManager.GetString("QuickPresets", resourceCulture);
            }
        }

        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }

        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }

        public static string MILock {
            get {
                return ResourceManager.GetString("MILock", resourceCulture);
            }
        }

        public static string Shizuku {
            get {
                return ResourceManager.GetString("Shizuku", resourceCulture);
            }
        }

        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        public static string CheckPermissions {
            get {
                return ResourceManager.GetString("CheckPermissions", resourceCulture);
            }
        }

        public static string OpenAppSettings {
            get {
                return ResourceManager.GetString("OpenAppSettings", resourceCulture);
            }
        }

        public static string GrantSelectedPermissions {
            get {
                return ResourceManager.GetString("GrantSelectedPermissions", resourceCulture);
            }
        }

        public static string OptimizeNotifications {
            get {
                return ResourceManager.GetString("OptimizeNotifications", resourceCulture);
            }
        }

        public static string DisableBatteryOptimization {
            get {
                return ResourceManager.GetString("DisableBatteryOptimization", resourceCulture);
            }
        }

        public static string ApplyAll {
            get {
                return ResourceManager.GetString("ApplyAll", resourceCulture);
            }
        }

        public static string SelectAllPermissions {
            get {
                return ResourceManager.GetString("SelectAllPermissions", resourceCulture);
            }
        }

        public static string DeselectAllPermissions {
            get {
                return ResourceManager.GetString("DeselectAllPermissions", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Scrcpy Tab
        // ═══════════════════════════════════════════════════════════════

        public static string ScrcpyDesc {
            get {
                return ResourceManager.GetString("ScrcpyDesc", resourceCulture);
            }
        }

        public static string KeepScreenOn {
            get {
                return ResourceManager.GetString("KeepScreenOn", resourceCulture);
            }
        }

        public static string LaunchScrcpy {
            get {
                return ResourceManager.GetString("LaunchScrcpy", resourceCulture);
            }
        }

        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }

        public static string ScreenshotDesc {
            get {
                return ResourceManager.GetString("ScreenshotDesc", resourceCulture);
            }
        }

        public static string ChooseSaveFolder {
            get {
                return ResourceManager.GetString("ChooseSaveFolder", resourceCulture);
            }
        }

        public static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }

        public static string TakeScreenshot {
            get {
                return ResourceManager.GetString("TakeScreenshot", resourceCulture);
            }
        }

        public static string ScreenRecord {
            get {
                return ResourceManager.GetString("ScreenRecord", resourceCulture);
            }
        }

        public static string ScreenRecordDesc {
            get {
                return ResourceManager.GetString("ScreenRecordDesc", resourceCulture);
            }
        }

        public static string DurationSeconds {
            get {
                return ResourceManager.GetString("DurationSeconds", resourceCulture);
            }
        }

        public static string RecordScreen {
            get {
                return ResourceManager.GetString("RecordScreen", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Network Tab
        // ═══════════════════════════════════════════════════════════════

        public static string NetworkStatus {
            get {
                return ResourceManager.GetString("NetworkStatus", resourceCulture);
            }
        }

        public static string ReadNetworkStatus {
            get {
                return ResourceManager.GetString("ReadNetworkStatus", resourceCulture);
            }
        }

        public static string WiFi {
            get {
                return ResourceManager.GetString("WiFi", resourceCulture);
            }
        }

        public static string WiFiDesc {
            get {
                return ResourceManager.GetString("WiFiDesc", resourceCulture);
            }
        }

        public static string SSID {
            get {
                return ResourceManager.GetString("SSID", resourceCulture);
            }
        }

        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }

        public static string DisconnectWiFi {
            get {
                return ResourceManager.GetString("DisconnectWiFi", resourceCulture);
            }
        }

        public static string CheckWiFi {
            get {
                return ResourceManager.GetString("CheckWiFi", resourceCulture);
            }
        }

        public static string Bluetooth {
            get {
                return ResourceManager.GetString("Bluetooth", resourceCulture);
            }
        }

        public static string BluetoothDesc {
            get {
                return ResourceManager.GetString("BluetoothDesc", resourceCulture);
            }
        }

        public static string ScanBluetooth {
            get {
                return ResourceManager.GetString("ScanBluetooth", resourceCulture);
            }
        }

        public static string AirplaneMode {
            get {
                return ResourceManager.GetString("AirplaneMode", resourceCulture);
            }
        }

        public static string AirplaneModeDesc {
            get {
                return ResourceManager.GetString("AirplaneModeDesc", resourceCulture);
            }
        }

        public static string Hotspot {
            get {
                return ResourceManager.GetString("Hotspot", resourceCulture);
            }
        }

        public static string HotspotDesc {
            get {
                return ResourceManager.GetString("HotspotDesc", resourceCulture);
            }
        }

        public static string MobileNetwork {
            get {
                return ResourceManager.GetString("MobileNetwork", resourceCulture);
            }
        }

        public static string MobileNetworkDesc {
            get {
                return ResourceManager.GetString("MobileNetworkDesc", resourceCulture);
            }
        }

        public static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }

        public static string LocaleDesc {
            get {
                return ResourceManager.GetString("LocaleDesc", resourceCulture);
            }
        }

        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }

        public static string ApplyLocale {
            get {
                return ResourceManager.GetString("ApplyLocale", resourceCulture);
            }
        }

        public static string CheckLocale {
            get {
                return ResourceManager.GetString("CheckLocale", resourceCulture);
            }
        }

        public static string BlockMIUIAds {
            get {
                return ResourceManager.GetString("BlockMIUIAds", resourceCulture);
            }
        }

        public static string BlockGoogleAds {
            get {
                return ResourceManager.GetString("BlockGoogleAds", resourceCulture);
            }
        }

        public static string BlockAllAds {
            get {
                return ResourceManager.GetString("BlockAllAds", resourceCulture);
            }
        }

        public static string RestoreMIUIAds {
            get {
                return ResourceManager.GetString("RestoreMIUIAds", resourceCulture);
            }
        }

        public static string RestoreGoogleAds {
            get {
                return ResourceManager.GetString("RestoreGoogleAds", resourceCulture);
            }
        }

        public static string CheckAdBlockStatus {
            get {
                return ResourceManager.GetString("CheckAdBlockStatus", resourceCulture);
            }
        }

        public static string AdBlockDNS {
            get {
                return ResourceManager.GetString("AdBlockDNS", resourceCulture);
            }
        }

        public static string AdBlockDNSDesc {
            get {
                return ResourceManager.GetString("AdBlockDNSDesc", resourceCulture);
            }
        }

        public static string EnableAdBlock {
            get {
                return ResourceManager.GetString("EnableAdBlock", resourceCulture);
            }
        }

        public static string DefaultDNS {
            get {
                return ResourceManager.GetString("DefaultDNS", resourceCulture);
            }
        }

        public static string CheckDNS {
            get {
                return ResourceManager.GetString("CheckDNS", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // System Tab
        // ═══════════════════════════════════════════════════════════════

        public static string BatteryInfo {
            get {
                return ResourceManager.GetString("BatteryInfo", resourceCulture);
            }
        }

        public static string ReadBatteryInfo {
            get {
                return ResourceManager.GetString("ReadBatteryInfo", resourceCulture);
            }
        }

        public static string DisplayInfo {
            get {
                return ResourceManager.GetString("DisplayInfo", resourceCulture);
            }
        }

        public static string ReadDisplayInfo {
            get {
                return ResourceManager.GetString("ReadDisplayInfo", resourceCulture);
            }
        }

        public static string LockHz {
            get {
                return ResourceManager.GetString("LockHz", resourceCulture);
            }
        }

        public static string LockHzDesc {
            get {
                return ResourceManager.GetString("LockHzDesc", resourceCulture);
            }
        }

        public static string LockAt {
            get {
                return ResourceManager.GetString("LockAt", resourceCulture);
            }
        }

        public static string ReadHz {
            get {
                return ResourceManager.GetString("ReadHz", resourceCulture);
            }
        }

        public static string ApplyHzLock {
            get {
                return ResourceManager.GetString("ApplyHzLock", resourceCulture);
            }
        }

        public static string SmoothUI {
            get {
                return ResourceManager.GetString("SmoothUI", resourceCulture);
            }
        }

        public static string ApplyHzLockFull {
            get {
                return ResourceManager.GetString("ApplyHzLockFull", resourceCulture);
            }
        }

        public static string RestoreAdaptiveHz {
            get {
                return ResourceManager.GetString("RestoreAdaptiveHz", resourceCulture);
            }
        }

        public static string DeviceInfoTitle {
            get {
                return ResourceManager.GetString("DeviceInfoTitle", resourceCulture);
            }
        }

        public static string DeviceInfoDesc {
            get {
                return ResourceManager.GetString("DeviceInfoDesc", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Tweaks Tab
        // ═══════════════════════════════════════════════════════════════

        public static string DPI {
            get {
                return ResourceManager.GetString("DPI", resourceCulture);
            }
        }

        public static string DPIPresets {
            get {
                return ResourceManager.GetString("DPIPresets", resourceCulture);
            }
        }

        public static string SetDPI {
            get {
                return ResourceManager.GetString("SetDPI", resourceCulture);
            }
        }

        public static string ResetDPI {
            get {
                return ResourceManager.GetString("ResetDPI", resourceCulture);
            }
        }

        public static string AnimationSpeed {
            get {
                return ResourceManager.GetString("AnimationSpeed", resourceCulture);
            }
        }

        public static string SetAnimation {
            get {
                return ResourceManager.GetString("SetAnimation", resourceCulture);
            }
        }

        public static string NavigationMode {
            get {
                return ResourceManager.GetString("NavigationMode", resourceCulture);
            }
        }

        public static string GestureNav {
            get {
                return ResourceManager.GetString("GestureNav", resourceCulture);
            }
        }

        public static string ThreeButtonNav {
            get {
                return ResourceManager.GetString("ThreeButtonNav", resourceCulture);
            }
        }

        public static string StatusBar {
            get {
                return ResourceManager.GetString("StatusBar", resourceCulture);
            }
        }

        public static string StatusBarDesc {
            get {
                return ResourceManager.GetString("StatusBarDesc", resourceCulture);
            }
        }

        public static string BatteryPercentage {
            get {
                return ResourceManager.GetString("BatteryPercentage", resourceCulture);
            }
        }

        public static string DeveloperOptions {
            get {
                return ResourceManager.GetString("DeveloperOptions", resourceCulture);
            }
        }

        public static string StayAwake {
            get {
                return ResourceManager.GetString("StayAwake", resourceCulture);
            }
        }

        public static string ShowTaps {
            get {
                return ResourceManager.GetString("ShowTaps", resourceCulture);
            }
        }

        public static string PointerLocation {
            get {
                return ResourceManager.GetString("PointerLocation", resourceCulture);
            }
        }

        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }

        public static string ScreenTimeout {
            get {
                return ResourceManager.GetString("ScreenTimeout", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Advanced Tab
        // ═══════════════════════════════════════════════════════════════

        public static string DeviceSpoof {
            get {
                return ResourceManager.GetString("DeviceSpoof", resourceCulture);
            }
        }

        public static string DeviceSpoofDesc {
            get {
                return ResourceManager.GetString("DeviceSpoofDesc", resourceCulture);
            }
        }

        public static string UnlockFPS {
            get {
                return ResourceManager.GetString("UnlockFPS", resourceCulture);
            }
        }

        public static string UnlockFPSDesc {
            get {
                return ResourceManager.GetString("UnlockFPSDesc", resourceCulture);
            }
        }

        public static string ShizukuIntegration {
            get {
                return ResourceManager.GetString("ShizukuIntegration", resourceCulture);
            }
        }

        public static string ShizukuIntegrationDesc {
            get {
                return ResourceManager.GetString("ShizukuIntegrationDesc", resourceCulture);
            }
        }

        public static string StartShizuku {
            get {
                return ResourceManager.GetString("StartShizuku", resourceCulture);
            }
        }

        public static string AppOps {
            get {
                return ResourceManager.GetString("AppOps", resourceCulture);
            }
        }

        public static string AppOpsDesc {
            get {
                return ResourceManager.GetString("AppOpsDesc", resourceCulture);
            }
        }

        public static string CheckAppOps {
            get {
                return ResourceManager.GetString("CheckAppOps", resourceCulture);
            }
        }

        public static string SetAppOps {
            get {
                return ResourceManager.GetString("SetAppOps", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Fastboot Tab
        // ═══════════════════════════════════════════════════════════════

        public static string FastbootDevices {
            get {
                return ResourceManager.GetString("FastbootDevices", resourceCulture);
            }
        }

        public static string FlashImage {
            get {
                return ResourceManager.GetString("FlashImage", resourceCulture);
            }
        }

        public static string FlashImageDesc {
            get {
                return ResourceManager.GetString("FlashImageDesc", resourceCulture);
            }
        }

        public static string ChooseImage {
            get {
                return ResourceManager.GetString("ChooseImage", resourceCulture);
            }
        }

        public static string Partition {
            get {
                return ResourceManager.GetString("Partition", resourceCulture);
            }
        }

        public static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }

        public static string FlashROM {
            get {
                return ResourceManager.GetString("FlashROM", resourceCulture);
            }
        }

        public static string FlashROMDesc {
            get {
                return ResourceManager.GetString("FlashROMDesc", resourceCulture);
            }
        }

        public static string ChooseROMFolder {
            get {
                return ResourceManager.GetString("ChooseROMFolder", resourceCulture);
            }
        }

        public static string FlashCurrentSlot {
            get {
                return ResourceManager.GetString("FlashCurrentSlot", resourceCulture);
            }
        }

        public static string FlashAndLock {
            get {
                return ResourceManager.GetString("FlashAndLock", resourceCulture);
            }
        }

        public static string CancelFlash {
            get {
                return ResourceManager.GetString("CancelFlash", resourceCulture);
            }
        }

        public static string FactoryReset {
            get {
                return ResourceManager.GetString("FactoryReset", resourceCulture);
            }
        }

        public static string FactoryResetDesc {
            get {
                return ResourceManager.GetString("FactoryResetDesc", resourceCulture);
            }
        }

        public static string SetActiveSlot {
            get {
                return ResourceManager.GetString("SetActiveSlot", resourceCulture);
            }
        }

        public static string BootTemp {
            get {
                return ResourceManager.GetString("BootTemp", resourceCulture);
            }
        }

        public static string OEMUnlock {
            get {
                return ResourceManager.GetString("OEMUnlock", resourceCulture);
            }
        }

        public static string OEMLock {
            get {
                return ResourceManager.GetString("OEMLock", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Log & Status Messages
        // ═══════════════════════════════════════════════════════════════

        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }

        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }

        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }

        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }

        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }

        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }

        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }

        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }

        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // MessageBox Messages
        // ═══════════════════════════════════════════════════════════════

        public static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }

        public static string SelectAtLeastOneApp {
            get {
                return ResourceManager.GetString("SelectAtLeastOneApp", resourceCulture);
            }
        }

        public static string SelectAtLeastOnePermission {
            get {
                return ResourceManager.GetString("SelectAtLeastOnePermission", resourceCulture);
            }
        }

        public static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }

        public static string DeviceNotReady {
            get {
                return ResourceManager.GetString("DeviceNotReady", resourceCulture);
            }
        }

        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Permission Labels
        // ═══════════════════════════════════════════════════════════════

        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }

        public static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }

        public static string Vibrate {
            get {
                return ResourceManager.GetString("Vibrate", resourceCulture);
            }
        }

        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }

        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }

        public static string Microphone {
            get {
                return ResourceManager.GetString("Microphone", resourceCulture);
            }
        }

        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }

        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }

        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }

        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }

        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Welcome Window
        // ═══════════════════════════════════════════════════════════════

        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }

        public static string QuickGuide {
            get {
                return ResourceManager.GetString("QuickGuide", resourceCulture);
            }
        }

        public static string ConnectPhone {
            get {
                return ResourceManager.GetString("ConnectPhone", resourceCulture);
            }
        }

        public static string ConnectPhoneDesc {
            get {
                return ResourceManager.GetString("ConnectPhoneDesc", resourceCulture);
            }
        }

        public static string EnableUSBDebugging {
            get {
                return ResourceManager.GetString("EnableUSBDebugging", resourceCulture);
            }
        }

        public static string EnableUSBDebuggingDesc {
            get {
                return ResourceManager.GetString("EnableUSBDebuggingDesc", resourceCulture);
            }
        }

        public static string AllowUSBDebugging {
            get {
                return ResourceManager.GetString("AllowUSBDebugging", resourceCulture);
            }
        }

        public static string AllowUSBDebuggingDesc {
            get {
                return ResourceManager.GetString("AllowUSBDebuggingDesc", resourceCulture);
            }
        }

        public static string UsefulTips {
            get {
                return ResourceManager.GetString("UsefulTips", resourceCulture);
            }
        }

        public static string Tip1 {
            get {
                return ResourceManager.GetString("Tip1", resourceCulture);
            }
        }

        public static string Tip2 {
            get {
                return ResourceManager.GetString("Tip2", resourceCulture);
            }
        }

        public static string Tip3 {
            get {
                return ResourceManager.GetString("Tip3", resourceCulture);
            }
        }

        public static string Tip4 {
            get {
                return ResourceManager.GetString("Tip4", resourceCulture);
            }
        }

        public static string Tip5 {
            get {
                return ResourceManager.GetString("Tip5", resourceCulture);
            }
        }

        public static string Tip6 {
            get {
                return ResourceManager.GetString("Tip6", resourceCulture);
            }
        }

        public static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }

        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Language
        // ═══════════════════════════════════════════════════════════════

        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }

        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Additional Status Messages
        // ═══════════════════════════════════════════════════════════════

        public static string NoDeviceHint {
            get {
                return ResourceManager.GetString("NoDeviceHint", resourceCulture);
            }
        }

        public static string DeviceNotReadyHint {
            get {
                return ResourceManager.GetString("DeviceNotReadyHint", resourceCulture);
            }
        }

        public static string WaitingForDevice {
            get {
                return ResourceManager.GetString("WaitingForDevice", resourceCulture);
            }
        }

        public static string DeviceReady {
            get {
                return ResourceManager.GetString("DeviceReady", resourceCulture);
            }
        }

        public static string ROMInfo {
            get {
                return ResourceManager.GetString("ROMInfo", resourceCulture);
            }
        }

        public static string NotScanned {
            get {
                return ResourceManager.GetString("NotScanned", resourceCulture);
            }
        }

        public static string ScannedFromCache {
            get {
                return ResourceManager.GetString("ScannedFromCache", resourceCulture);
            }
        }

        public static string AppsFound {
            get {
                return ResourceManager.GetString("AppsFound", resourceCulture);
            }
        }

        public static string ScanningComplete {
            get {
                return ResourceManager.GetString("ScanningComplete", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Additional Button Labels
        // ═══════════════════════════════════════════════════════════════

        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }

        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }

        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }

        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Additional Status & Info
        // ═══════════════════════════════════════════════════════════════

        public static string NoAPKInFolder {
            get {
                return ResourceManager.GetString("NoAPKInFolder", resourceCulture);
            }
        }

        public static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }

        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }

        public static string OperationComplete {
            get {
                return ResourceManager.GetString("OperationComplete", resourceCulture);
            }
        }

        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }

        public static string DeviceWillReboot {
            get {
                return ResourceManager.GetString("DeviceWillReboot", resourceCulture);
            }
        }

        public static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }

        public static string DestructiveWarning {
            get {
                return ResourceManager.GetString("DestructiveWarning", resourceCulture);
            }
        }

        public static string CannotUndo {
            get {
                return ResourceManager.GetString("CannotUndo", resourceCulture);
            }
        }

        public static string DataWillBeDeleted {
            get {
                return ResourceManager.GetString("DataWillBeDeleted", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Log Prefixes
        // ═══════════════════════════════════════════════════════════════

        public static string LogOK {
            get {
                return ResourceManager.GetString("LogOK", resourceCulture);
            }
        }

        public static string LogFAIL {
            get {
                return ResourceManager.GetString("LogFAIL", resourceCulture);
            }
        }

        public static string LogWARN {
            get {
                return ResourceManager.GetString("LogWARN", resourceCulture);
            }
        }

        public static string LogINFO {
            get {
                return ResourceManager.GetString("LogINFO", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Additional UI Elements
        // ═══════════════════════════════════════════════════════════════

        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        public static string CustomPackage {
            get {
                return ResourceManager.GetString("CustomPackage", resourceCulture);
            }
        }

        public static string WiFiSSIDPlaceholder {
            get {
                return ResourceManager.GetString("WiFiSSIDPlaceholder", resourceCulture);
            }
        }

        public static string WiFiPasswordPlaceholder {
            get {
                return ResourceManager.GetString("WiFiPasswordPlaceholder", resourceCulture);
            }
        }

        public static string LocalFilePath {
            get {
                return ResourceManager.GetString("LocalFilePath", resourceCulture);
            }
        }

        public static string RemoteDevicePath {
            get {
                return ResourceManager.GetString("RemoteDevicePath", resourceCulture);
            }
        }

        public static string RemoteFilePath {
            get {
                return ResourceManager.GetString("RemoteFilePath", resourceCulture);
            }
        }

        public static string SaveFolderPath {
            get {
                return ResourceManager.GetString("SaveFolderPath", resourceCulture);
            }
        }

        public static string ScreenshotSavePath {
            get {
                return ResourceManager.GetString("ScreenshotSavePath", resourceCulture);
            }
        }

        public static string RecordSavePath {
            get {
                return ResourceManager.GetString("RecordSavePath", resourceCulture);
            }
        }

        public static string CustomLocale {
            get {
                return ResourceManager.GetString("CustomLocale", resourceCulture);
            }
        }

        public static string FastbootImageFile {
            get {
                return ResourceManager.GetString("FastbootImageFile", resourceCulture);
            }
        }

        public static string ShizukuCustomPerm {
            get {
                return ResourceManager.GetString("ShizukuCustomPerm", resourceCulture);
            }
        }

        public static string CustomAppOps {
            get {
                return ResourceManager.GetString("CustomAppOps", resourceCulture);
            }
        }

        public static string CustomPermission {
            get {
                return ResourceManager.GetString("CustomPermission", resourceCulture);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Permission Category Names
        // ═══════════════════════════════════════════════════════════════

        public static string PermGroupNotifications {
            get {
                return ResourceManager.GetString("PermGroupNotifications", resourceCulture);
            }
        }

        public static string PermGroupBackground {
            get {
                return ResourceManager.GetString("PermGroupBackground", resourceCulture);
            }
        }

        public static string PermGroupBattery {
            get {
                return ResourceManager.GetString("PermGroupBattery", resourceCulture);
            }
        }

        public static string PermGroupMIUI {
            get {
                return ResourceManager.GetString("PermGroupMIUI", resourceCulture);
            }
        }

        public static string PermGroupNetwork {
            get {
                return ResourceManager.GetString("PermGroupNetwork", resourceCulture);
            }
        }

        public static string PermGroupLocation {
            get {
                return ResourceManager.GetString("PermGroupLocation", resourceCulture);
            }
        }

        public static string PermGroupCameraMic {
            get {
                return ResourceManager.GetString("PermGroupCameraMic", resourceCulture);
            }
        }

        public static string PermGroupStorage {
            get {
                return ResourceManager.GetString("PermGroupStorage", resourceCulture);
            }
        }

        public static string PermGroupDisplay {
            get {
                return ResourceManager.GetString("PermGroupDisplay", resourceCulture);
            }
        }

        public static string PermGroupOther {
            get {
                return ResourceManager.GetString("PermGroupOther", resourceCulture);
            }
        }

        public static string PermGroupShizuku {
            get {
                return ResourceManager.GetString("PermGroupShizuku", resourceCulture);
            }
        }
    }
}
